#!/usr/bin/env bash
# Zed launches this as OpenClaw's ACP agent.
#
# Unlike Hermes and Prime Agent, `openclaw acp` is not self-contained: it is a bridge CLIENT
# of OpenClaw's WebSocket Gateway, and with no gateway listening it exits immediately with
# "ACP bridge failed: connect ECONNREFUSED 127.0.0.1:18789" -- which Zed would surface only
# as an agent that refuses to start.
#
# The gateway is started lazily here rather than installed as a systemd user service, because
# this machine has a real memory ceiling (WSL is capped at 14 GB after an earlier OOM crisis)
# and a permanently-resident daemon for a harness used occasionally is a poor trade. Started
# this way it appears the first time OpenClaw is opened in Zed and is then reused.
#
# --allow-unconfigured is required because openclaw.json carries no `gateway` block: that file
# is GENERATED by sync-harnesses.sh from llama-swap.yaml, so anything hand-added to it is
# erased on the next slot change. The flag is the documented way to start without demanding
# gateway.mode=local in config, and it explicitly does not rewrite the file.
set -uo pipefail
export HOME=/home/priya
export PATH="/home/priya/.nvm/versions/node/v24.18.0/bin:/usr/local/bin:/usr/bin:/bin"
PORT=18789

port_open() { timeout 1 bash -c "exec 3<>/dev/tcp/127.0.0.1/$PORT" 2>/dev/null; }

if ! port_open; then
  nohup openclaw gateway run --allow-unconfigured --bind loopback \
    >> /tmp/openclaw-gateway.log 2>&1 &
  for _ in $(seq 1 90); do
    port_open && break
    sleep 1
  done
fi

if ! port_open; then
  echo "openclaw gateway failed to come up on 127.0.0.1:$PORT; see /tmp/openclaw-gateway.log" >&2
  tail -5 /tmp/openclaw-gateway.log >&2
  exit 1
fi

exec openclaw acp
